-- AlterTable
ALTER TABLE `Joueur` ADD COLUMN `bonusPaReveil` INTEGER NOT NULL DEFAULT 0,
    MODIFY `causeMort` ENUM('ATTAQUE_NOCTURNE', 'COMBAT_EXTERIEUR', 'FAIM', 'SOIF', 'INFECTION', 'EAU_CONTAMINEE') NULL;
